<?php

/**
 * @file
 * Contains hooks related to OS2Forms REST API module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\os2forms_rest_api\WebformHelper;

/**
 * Implements hook_webform_third_party_settings_form_alter().
 *
 * @see WebformHelper::webformThirdPartySettingsFormAlter()
 *
 * @phpstan-param array<string, mixed> $form
 */
function os2forms_rest_api_webform_third_party_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  \Drupal::service(WebformHelper::class)->webformThirdPartySettingsFormAlter($form, $form_state);
}

/**
 * Implements hook_file_download().
 *
 * @phpstan-return int|array<string, string>|null
 */
function os2forms_rest_api_file_download(string $uri) {
  return \Drupal::service(WebformHelper::class)->fileDownload($uri);
}
